Ajout du ppi et légères modifications pour les create_process. refs #24
git-svn-id: https://www.etud.insa-toulouse.fr/svn/projet_tut_OS/trunk/tacos@699 ab7442c9-e926-469a-b309-6eee04cae01a

diff --git a/applications/Makefile b/applications/Makefile
--- a/applications/Makefile
+++ b/applications/Makefile
@@ -1,4 +1,5 @@
 OBJ=cube top matrix test sem_ping sem_pong test_sig
+SUBDIRS=mishell
 LIBS=../lib/libc.a ../lib/libsystem.a 
 INCLUDES=-I../include/ -I../libc/include/
 CFLAGS=-W -Wall -g -nostdlib -nostdinc -nostartfiles -nodefaultlibs -fno-builtin -I`pwd` -m32
@@ -8,7 +9,11 @@ BIN=../bin/
 SRCS=*.c
 
 all: $(OBJ)
-	make -C mishell
+	@for i in $(SUBDIRS); do \
+		printf "\033[1m>>> [$$i]\033[0m\n"; \
+		$(MAKE) -s -C $$i; \
+		if [ $$? = 0 ]; then printf "\033[1m<<< [$$i] [OK]\033[0m\n"; else printf "\033[31m\033[1m<<< [$$i] [FAIL]\033[0m\n"; exit 1; fi; \
+		done
 
 cube: cube.o
 	$(LD) -o $(BIN)$@ $^ $(LIBS)
@@ -38,6 +43,11 @@ depend: $(SRCS)
 	makedepend -Y $(INCLUDES) -- $(CFLAGS) -- $^
 
 clean:
+	@for i in $(SUBDIRS); do \
+		printf "\033[1m>>> [$$i]\033[0m\n"; \
+		$(MAKE) -s -C $$i clean; \
+		printf "\033[1m<<< [$$i]\033[0m\n"; \
+	done
 	rm -f $(OBJ) *.o *.a
 	rm -f $(BIN)*
 
